---
version: '2'
services:
  client:
    build: .
  elasticsearch:
    image: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
  kibana:
    image: kibana
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://172.17.42.1:9200"
